version: '3'
services:
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin-pass
    ports:
      - "5672:5672"

  worker:
    build: .
    entrypoint: ["celery"]
    command: ["worker", "-A", "app.worker", "--loglevel=info"]
    depends_on:
      - rabbit

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbit
  
  